name: Deploy Production

on:
  push:
    tags:
      - 'v*'
env:
  APP_YAML: ${{ secrets.APP_YAML }}
  GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create .env file
      run: echo $APP_YAML | base64 --decode -i > ./app.yaml
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        export_default_credentials: true
    - name: Use gcloud CLI
      run: |
        gcloud app deploy --quiet app.yaml --version=$GITHUB_REF_NAME_SLUG
